<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="F_UpdateEventTimestampWithSystemTime" Id="{d37c28c3-1f20-4d00-b15c-7e62b46e36a7}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_UpdateEventTimestampWithSystemTime
VAR_INPUT
	stEvent : REFERENCE TO ST_Event;
END_VAR
VAR
	fbGetSystemTime : GETSYSTEMTIME; //Get system time
	stFileTIme : T_FILETIME; //Filetime structure
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbGetSystemTIme(
	timeLoDW => stFileTIme.dwLowDateTime, 
	timeHiDW => stFileTIme.dwHighDateTime);
	
stEvent.dtTimestamp := FILETIME_TO_DT(fileTime := stFileTime);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>